version: '3.7'
services:
  frontend:
    build: ./react
    container_name: frontend
    ports:
      - "3000:3000"
    # working_dir: /app
    # volumes:
    #   - .:/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
